== Eclipse MicroProfile Config 1.2

The majority of applications need to be configured based on a running environment. It must be possible to modify configuration data from outside an application so that the application itself does not need to be repackaged.

The configuration data can come from different locations and in different formats (e.g. system properties, system environment variables, .properties, .xml, datasource). We call these config locations ConfigSources. If the same property is defined in multiple ConfigSources, we apply a policy to specify which one of the values will effectively be used.

Under some circumstances, some data sources may change dynamically. The changed values should be fed into the client without the need for restarting the application. This requirement is particularly important for microservices running in a cloud environment. The MicroProfile Config approach allows to pick up configured values immediately after they got changed.

=== Design
The current configuration of an application can be accessed via `ConfigProvider#getConfig()`.

A Config consists of the information collected from the registered org.eclipse.microprofile.config.spi.ConfigSource s. These ConfigSource s get sorted according to their ordinal. That way it is possible to overwrite configuration with lower importance from outside.

By default there are 3 default ConfigSources:

* System.getProperties() (ordinal=400)
* System.getenv() (ordinal=300)
* all `META-INF/microprofile-config.properties` files on the ClassPath. (default ordinal=100, separately configurable via a config_ordinal property inside each file)

Therefore, the default values can be specified in the above files packaged with the application and the value can be overwritten later for each deployment. A higher ordinal number takes precedence over a lower number.

=== In our case

Since we are building a microservice based application, each of the services is available on its own URL. Since each service can run on a separate machine its not a good idea to hardcode the urls in the code. These string are perfect candidates to be externalized in a config.

All of our microservices use `Users` microservice, so let us go to `Authors` project and create `microprofile-config.properties` file in `src/main/resources/META-INF/` folder and put:

[source]
----
usersServiceUrl=http://localhost:9100/users
----

In `AuthorsRepository` we will replace the static string with

[source, java]
----
@Inject
@ConfigProperty(name = "usersServiceUrl", defaultValue = "http://localhost:9100/users")
private String usersUrl;
----

@ConfigProperty annotation tells the server to scan the config file, search for the property and inject it in the `usersUrls` variable.
This annotation provides an optional fallback option `defaultValue` which we will use for out local development.

The same configuration should be applied to `Content`, `Subscribers`.

The `Gui` project uses all of the other services, so we should put all th URLs in the config `src/main/webapp/META-INF/microprofile-config.properties`:

[source]
----
usersServiceUrl=http://localhost:9100/users
authorsServiceUrl=http://localhost:9110/authors
contentServiceUrl=http://localhost:9120/content
subscribersServiceUrl=http://localhost:9130/subscribers
----

and inject all of them in `GUIResource`

[source, java]
----
@Inject
@ConfigProperty(name = "usersServiceUrl", defaultValue = "http://localhost:9100/users")
private String usersUrl;
@Inject
@ConfigProperty(name = "authorsServiceUrl", defaultValue = "http://localhost:9110/authors")
private String authorsUrl;
@Inject
@ConfigProperty(name = "contentServiceUrl", defaultValue = "http://localhost:9120/content")
private String contentUrl;
@Inject
@ConfigProperty(name = "subscribersServiceUrl", defaultValue = "http://localhost:9130/subscribers")
private String subscribersUrl;
----

As we can see, there are always fallback options available.

More information about the Configuration specification is available at:

* http://microprofile.io/project/eclipse/microprofile-config
* https://github.com/eclipse/microprofile-config/releases/tag/1.2