== Config

The majority of applications need to be configured based on a running environment. It must be possible to modify configuration data from outside an application so that the application itself does not need to be repackaged.

The configuration data can come from different locations and in different formats (e.g. system properties, system environment variables, .properties, .xml, datasource). We call these config locations ConfigSources. If the same property is defined in multiple ConfigSources, we apply a policy to specify which one of the values will effectively be used.

Under some circumstances, some data sources may change dynamically. The changed values should be fed into the client without the need for restarting the application. This requirement is particularly important for microservices running in a cloud environment. The MicroProfile Config approach allows to pick up configured values immediately after they got changed.

=== Design
The current configuration of an application can be accessed via `ConfigProvider#getConfig()`.

A Config consists of the information collected from the registered `org.eclipse.microprofile.config.spi.ConfigSource` s.
These `ConfigSource` s get sorted according to their ordinal.
That way it is possible to overwrite configuration with lower importance from outside.

By default there are 3 default config sources:

* System.getProperties() (ordinal=400)
* System.getenv() (ordinal=300)
* all `META-INF/microprofile-config.properties` files on the ClassPath. (default ordinal=100, separately configurable via a config_ordinal property inside each file)

Therefore, the default values can be specified in the above files packaged with the application and the value can be overwritten later for each deployment. A higher ordinal number takes precedence over a lower number.

=== In our case

Since we are building a microservice based application, each of the services is available on its own URL.
As each service can run on a separate machine it's not a good idea to hardcode the URLs in the code (as we've done in the beginning).
These string are perfect candidates to be externalized in a config.

All of our microservices use `Users` microservice, so let us go to _authors_ project and create `microprofile-config.properties` file in `src/main/resources/META-INF/` folder and put:

[source]
----
usersServiceUrl=http://localhost:9100/users
----

In `AuthorsResource` we will replace the static string with

[source, java]
----
@Inject
@ConfigProperty(name = "usersServiceUrl", defaultValue = "http://localhost:8081/users")
private String usersUrl;
----

`@ConfigProperty` annotation tells the server to scan the config sources, search for the property and inject it in the `usersUrls` variable.
This annotation provides an optional fallback option `defaultValue` which we will use for our local development.

The same configuration should be applied to _content_ and _subscribers_ projects.

The `Gui` project uses all of the other services, so we should put all th URLs in the config `src/main/resources/META-INF/microprofile-config.properties`:

[source]
----
usersServiceUrl=http://localhost:9100/users
authorsServiceUrl=http://localhost:9110/authors
contentServiceUrl=http://localhost:9120/content
subscribersServiceUrl=http://localhost:9130/subscribers
----

and inject all of them in `GUIResource`

[source, java]
----
@Inject
@ConfigProperty(name = "usersServiceUrl", defaultValue = "http://localhost:8081/users")
private String usersUrl;
@Inject
@ConfigProperty(name = "authorsServiceUrl", defaultValue = "http://localhost:8082/authors")
private String authorsUrl;
@Inject
@ConfigProperty(name = "contentServiceUrl", defaultValue = "http://localhost:8083/content")
private String contentUrl;
@Inject
@ConfigProperty(name = "subscribersServiceUrl", defaultValue = "http://localhost:8084/subscribers")
private String subscribersUrl;
----
As we can see, there are always fallback options available.

==== Environmental Variables

We are also able to set our configuration properties from outside the app via _Environmental variables_. Let us experiment! Remove the line `usersServiceUrl=http://localhost:9100/users` from the `microprofile-config.properties` and start it. Since we have the default fallback the app will still start with the default url.
But if we would like to make an external configuration, if for example you run the app in docker, you can do it with `-D<property=value> in the commandline:

[source,bash]
----
java -jar authors.jar -DusersServiceUrl=http://localhost:9100/users
----
Now the app will inject the specified url.

=== Additional exercise

Now lets find all places where we are still using `String` constants for service URL's and change them to support external configuration.

- `SubscribersResource`
- `AuthorClient`

---
More information about the Configuration specification is available at:

* http://microprofile.io/project/eclipse/microprofile-config
* https://github.com/eclipse/microprofile-config/releases/tag/1.2