== Role based access control with JWT

Application security is one of the most important topics in the software development.
Provided you don't write a _Hello world_ app, you will definitely reach the point when you want to start controlling the access to some of your resources or functionalities.
But surprisingly how many different approaches there are for that at least in the Java space.
There are quite a few standards and at the same time most of the teams or companies breed their own solutions.

There are two core building blocks of the application security: authentication and authorization.
The first one's goal is to check whether the actor performing the action with the app is the one that they are pretending to be.
The most common approach to authentication is by providing user name and password in a login page.
But you can also authenticate with certificates (ever connected to AWS VM?).
Or using a third party identity provider like Google, Twitter, Github, Facebook, etc.
At the end, there is an agent that checks the provided credentials and confirms that the authenticating person is the one that they claim to be.

Once a user is authenticated, they can go on and start working with the site.
However, not all the resources and functionalities should be available to anyone.
Some of the pages or features may only be accessible by users in a certain role (e.g. admin or manager).
And user with lesser permissions should not be allowed to access them.

The existing Java EE specs (JAX-RS, Servlet, EJB, JAX-WS) have very strong authorization support.
Since Java EE 8 there is a new spec (Java EE Security) that also tackles the authentication topic very well.
However, in a microservice app we need to go a level up.
Not only both building blocks should work seamlessly together, but this should happen in an environment, where not every microservice can perform checks.

Imagine if upon each request, all the services in our app should validate the requesting user and their role(s).
This means that all of them should have access to the identity provider.
And that they should spend the time and resources for all the checks.
Even though that those time and resources were already spent a moment ago by another service.

There must be a better way.
And it is provided by MicroProfile's Resource-based access control (RBAC) with JSON Web Token (JWT) specification.
The spec defines a token format of token that is generated by presumably one microservice (or if you prefer gateway) upon receiving and accepting user credentials.
This token comes in the form of a Base64 encoded JSON object, holding information about the authenticated user (like first and last name, email, user groups, etc.).
After its generation, it is passed along every other request in its `Authorization` header.
Even if the request spans more than one microservice, each of them can decode the token and see the details of the user that sent it.
Without the need to authenticate it again.

The token is signed and its signature is checked by the MicroProfile implementations prior to calling the protected resources to avoid tempering with it.
The runtimes will also check if the token has expired (it usually expires in an hour).
In all such cases it will be the application server that will return response code 401 even before the request reaches the application code.
So in such cases the login gateway should be requested again to generate a new valid token.

In this chapter we will show you how the user service will generate such JWT string.
Then we will show you how the GUI service will use that in all the subsequent calls to other microservices and how it will decide whether a requester is authenticated or not.
After that we will see how microservice can define whether users are allowed to access certain resource or not.
Finally, we will find out the way that user information can be extracted from the JSON web token.

Let's start with the authentication.

=== User authentication

The authentication of our Magazine Manager application at the moment resembles quite a lot the authentication of a typical monolith app.
There is a filter that intercepts the incoming requests.
It gets hold of a session scoped bean, which is used to check whether there is already a logged user.
If not, it returns unauthorized response code for all protected resources.
On the other hand, if the requested page is the login one and if there is a successful login after that, the logged user is set in the mentioned session scoped bean.
The only difference so far is that the authentication functionality is running on a separate microservice.

This approach, however, suffers from a few flows.
The GUI service here becomes a single point of failure.
If it goes down and is later restarted, all the session cookies are invalidated.
Which means that the users will have to login again, which is unpleasant.
We also can't scale up the GUI service without burdening the load balancer with techniques like sticky sessions (to remember which user went to which instance of the service).

We can definitely do better by seizing to rely on the `JSESSIONID` cookie.
In the next lines we will make the users microservice return us a JWT token upon successful login (or registration).
We will return that to the GUI microservice, which will simply put it in a cookie.
Then it will be browser's responsibility to return that cookie upon each subsequent request.

The GUI service's filter will only check if the cookie is present.
It will be the job of the other microservices to check its validity.
In either case the services will return response code 401 when something is wrong: the GUI service if the cookie is missing, the other services if it is not valid.
Then the HTML files will pick that response code and will forward the flow to the login page.

Let's first improve the login and registration processes.
So far, upon successful credention validation, _users_ microservice's `UserResource` only returns status OK without any payload.
Here we will generate a JSON web token (JWT) and will attach it to the designated response header.
For the token generation we will use the `JWTUtils` class.
It hides all the details of creating the JSON object, encoding it to Base64 and signing it with the private key packaged with the app (don't do that with productive apps - private keys should not be part of version control!).

So, in `UserResource::findUserByEmailAndPassword`, if we find a user in the repository, we will generate a JWT and will attach it in the Authorization header, prefixed with the string "Bearer ":

[source,java]
----
public Response findUserByEmailAndPassword(JsonObject loginDetails) {
    return userRepository.findByLoginDetails(loginDetails.getString("email"), loginDetails.getString("password"))
            .map(user -> Response.ok(user.toJson()).header("Authorization", "Bearer " + JwtUtils.generateJWT(user)).build())
            .orElse(Response.status(Response.Status.UNAUTHORIZED).build());
}
----

TIP: The header name `Authorization` and the `Bearer` prefix (or schema) are standard for all the platforms that use JWT for authentication and authorization, not just for MicroProfile.

If we no go back to our `gui` service and more particularly to the `GUIResource` class.
It injects the session scoped `UserContext` class and the `login` method sets there the logged user upon successful login.
We want to get rid of the user context and put the JWT into a cookie.
Which later on will be checked by the filter.

Let's remove this piece of code first:

[source,java]
----
if (loginResponse.getStatus() == Response.Status.OK.getStatusCode()) {
    userContext.setLoggedUser(User.fromJson(loginResponse.readEntity(JsonObject.class)));
}
client.close();
return loginResponse;
----

And replace it with:

[source,java]
----
if (loginResponse.getStatus() == Response.Status.OK.getStatusCode()) {
    String headerString = loginResponse.getHeaderString("Authorization");
    // Cookies don't accept white space in their values
    // so we strip the "Bearer " prefix and only send the real token
    String token = headerString.substring("Bearer ".length());

    return Response.ok()
            .cookie(new NewCookie("Authorization", token))
            .build();
} else {
    return loginResponse;
}
----

Now the next requests that your browser sends to your app will contain the cookie with the JWT.

Next, it is time to check for the cookie existence in the `LoggedUserFilter` class.
Let's rework a bit the `filter` method and replace the `UserContext` check there as well:

[source,java]
----
public void filter(ContainerRequestContext ctx) {
    String reqURI = ctx.getUriInfo().getPath();
    Cookie authCookie = ctx.getCookies().get("Authorization");

    if (authCookie == null &&
        WHITE_LIST.stream().noneMatch(reqURI.toLowerCase()::contains)) {
        ctx.abortWith(Response.status(Response.Status.UNAUTHORIZED).build());
    }
}
----

As an exercise, implement the same flow for the registration case:

. In `UserResource::addUser` generate the JWT and attach it as authorization header with bearer scheme
. In `GUIResource::register` attach the JWT (without the Bearer prefix) to the same cookie as in the `login` method.
. You may consider extracting some constants and methods here and there

Try out what you did by starting the _GUI_, _user_ and optionally _content_ microservices and logging in with bilbo@example.org and bilbo123.

=== Role based access control

=== JWT and user details
