== Rest client

The MicroProfile Rest Client builds on JAX-RS 2.0 client APIs to provide a type-safe approach for invoking RESTful services.
This means writing client applications with more model-centric code and less 'plumbing'.
Although these are client APIs, they are deployed in a server.

=== The interface

First, we start off with an interface that represents the remote service.
The methods of the interface should match the RESTful APIs of the opposite endpoint.
Let us use this approach in the _content_ microservice.
As it calls the _authors_ service, we will use the MicroProfile Rest Client to access it.
In order make a bean implementing this REST client available for injection, we also have to annotate it with `@RegisterRestClient`.

[source, java]
----
@Path("/authors")
@Produces(MediaType.APPLICATION_JSON)
@RegisterRestClient
public interface AuthorsRestClient {

    @GET
    @Path("/findByEmail/{email}")
    JsonObject findAuthorByEmail(@PathParam("email") String email);
}
----

So far we've configured the internal path of the REST call.
But we need to also tell the MicroProfile Rest Client implementation the baseUrl value for the remote endpoint.
For that, we use MicroProfile Config.
The config property to use is `<fullyQualifiedInterfaceName>/mp-rest/url`.
Let's put this in the `microprofile-config.properties` file:

[source,properties]
----
bg.jug.microprofile.hol.content.AuthorsRestClient/mp-rest/url=http://localhost:9110/
----

=== Using the client

We have successfully created and registered our type safe REST client.
Now we can inject it in the `AuthorClient` class.
The `@Inject` should be qualified with the `@RestClient` annotation.

[source, java]
----
@Inject
@RestClient
private AuthorsRestClient authorsRestClient;
----

Then modify slightly the `findAuthorByEmail` method:

[source, java]
----
public JsonObject findAuthorByEmail(String email) {
    return authorsRestClient.findAuthorByEmail(email)
}
----

So.. now it is all set!
Rebuild and run the _content_ service.
Then while making sure that the _authors_ service is also running, run a get request on http://localhost:9120/content/findById/3.
It should return an article along with its author.
But this time the author data should be obtained with the MicroProfile Rest Client that we developed.

=== Exception mapping

Since there is no standard specification on error to exception mapping for microservices, each microservice may define its own http error code on different situations.
In this case MicroProfile RestClient gives us the possibility to perform this mapping:

[source, java]
----
@Provider
public class AuthorExceptionMapper implements
        ResponseExceptionMapper<RuntimeException> {

    @Override
    public boolean handles(int statusCode, MultivaluedMap<String, Object> headers) {
        return statusCode == 404  // Not Found
                || statusCode == 409; // Conflict
    }

    @Override
    public RuntimeException toThrowable(Response response) {
        switch(response.getStatus()) {
            case 404: return new NullPointerException();
            case 409: return new RuntimeException();
        }
        return null;
    }

}
----

As a result, if our _authors_ microservice ever returns us 404, the mapper will convert it to NullPointerException.
While in case of 409, it will be just a RuntimeException.

In order to enable our exception mapper, we need to add `@RegisterProvider` annotation to the Rest client interface:

[source,java]
----
@Path("/")
@Produces(MediaType.APPLICATION_JSON)
@RegisterRestClient
@RegisterProvider(AuthorExceptionMapper.class)
public interface AuthorsRestClient {

    @GET
    @Path("/findByEmail/{email}")
    JsonObject findAuthorByEmail(@PathParam("email") String email);
}
----

